CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Ad NVARCHAR(50) NOT NULL,
    Soyad NVARCHAR(50) NOT NULL,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    Sifre NVARCHAR(256) NOT NULL,
    Rol NVARCHAR(20) NOT NULL
);
